name: phone_number_validation
description: Test task for TBR Group Software

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  get_it: ^7.2.0
  injectable: ^1.5.3
  flutter_bloc: ^8.1.1
  logger: ^1.1.0
  injectable_generator: ^1.5.4
  beamer: ^1.5.3
  json_annotation: ^4.7.0
  dio: ^4.0.6
  equatable: ^2.0.5
  path_provider: ^2.0.11

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.2.1
  flutter_lints: ^2.0.0

flutter:


  uses-material-design: true


